### ISSUE TITLE
Add esbuild

### ISSUE THREAD

**Issue by plastikfan** [Snivilization/nodejs-esm-starter#10]
See:

+ [esbuild javascript](https://esbuild.github.io/content-types/#javascript)

**Comment by plastikfan** [comment]
Actually, setting bundle: true, fixes the above error, but another error occurs:

```
> nodejs-esm-starter@1.0.0 test
> node test/tryout.js && node test/tryout.cjs

white: The answer is: 42
internal/url.js:258
  throw new ERR_INVALID_URL(input);
  ^

TypeError [ERR_INVALID_URL]: Invalid URL: .
    at onParseError (internal/url.js:258:9)
    at new URL (internal/url.js:334:5)
    at Object.<anonymous> (/home/plastikfan/dev/github/snivilization/nodejs-esm-starter/lib/starter.bundle.cjs:42:50)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/plastikfan/dev/github/snivilization/nodejs-esm-starter/test/tryout.cjs:2:20) {
  input: '.',
  code: 'ERR_INVALID_URL'
}
```

**Comment by plastikfan** [comment]
NB: esbuild does support reading input from a stream so it should be easy to integrate this into gulp with the pipe command.

**Comment by plastikfan** [comment]
not appropriate
