### ISSUE TITLE
Part 5

### ISSUE THREAD

**Issue by plastikfan** [Snivilization/nodejs-esm-starter#5]

**Comment by plastikfan** [comment]
NB: the build task manually copies the non js file text.txt asset. But really this is wat we need gulp for.

**Comment by plastikfan** [comment]
run into a major issue running rollup:

```
 ✘ plastikfan@Janus  ~/dev/github/snivilization/nodejs-esm-starter λ   chore/part-05-dual-mode ±  npx rollup -c

src/add.js, src/banner-in-colour.js, src/main.js → lib...
(!) Unresolved dependencies
https://rollupjs.org/guide/en/#warning-treating-module-as-external-dependency
fs (imported by src/banner-in-colour.js)
url (imported by src/banner-in-colour.js)
path (imported by src/banner-in-colour.js)
[!] Error: Module format cjs does not support top-level await. Use the "es" or "system" output formats rather.
Error: Module format cjs does not support top-level await. Use the "es" or "system" output formats rather.
    at error (/home/plastikfan/dev/github/snivilization/nodejs-esm-starter/node_modules/rollup/dist/shared/rollup.js:158:30)
    at Chunk.render (/home/plastikfan/dev/github/snivilization/nodejs-esm-starter/node_modules/rollup/dist/shared/rollup.js:14768:20)
    at /home/plastikfan/dev/github/snivilization/nodejs-esm-starter/node_modules/rollup/dist/shared/rollup.js:15938:52
    at Array.map (<anonymous>)
    at Bundle.addFinalizedChunksToBundle (/home/plastikfan/dev/github/snivilization/nodejs-esm-starter/node_modules/rollup/dist/shared/rollup.js:15936:34)
    at Bundle.generate (/home/plastikfan/dev/github/snivilization/nodejs-esm-starter/node_modules/rollup/dist/shared/rollup.js:15916:24)
    at async handleGenerateWrite (/home/plastikfan/dev/github/snivilization/nodejs-esm-starter/node_modules/rollup/dist/shared/rollup.js:23400:23)
    at async Promise.all (index 0)
    at async build (/home/plastikfan/dev/github/snivilization/nodejs-esm-starter/node_modules/rollup/dist/bin/rollup:1576:5)
    at async runRollup (/home/plastikfan/dev/github/snivilization/nodejs-esm-starter/node_modules/rollup/dist/bin/rollup:1730:21)

 ✘ plastikfan@Janus  ~/dev/github/snivilization/nodejs-esm-starter λ   chore/part-05-dual-mode ± 
```
